CREATE TABLE USERS
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE ,
    username CHARACTER VARYING (55) NOT NULL UNIQUE,
    password CHARACTER VARYING (255) NOT NULL,
    email CHARACTER VARYING (55) NOT NULL UNIQUE
);
